language: groovy
jdk:
- oraclejdk8
sudo: false

before_install:  
  - pip3 install --user -r pip-requirements.txt

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2/"

addons:
  apt:
    packages:
      - python3
      - python3-pip

script: "./travis-build.sh"
