language: groovy
jdk:
- oraclejdk8
sudo: false

before_install:  
  - pip3 install --user -r pip-requirements.txt

addons:
  apt:
    packages:
      - python3
      - python3-pip

script: "./travis-build.sh"
